name: mobile_blitzbudget
description: A cross platform application for mobile IOS, Android and Mobile web
version: 1.0.0+1

environment:
  sdk: ">=2.10.0-0 <3.0.0"

dependencies:
  english_words: ^3.1.5
  flutter_lorem: ^1.1.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  mdi: ^3.0.0
  flutter_svg: ^0.19.0
  http: ^0.12.2
  flutter_secure_storage: ^3.3.4
  email_validator: ^1.0.5
  shared_preferences: ^0.5.12+4
  dartz: ^0.9.2
  equatable: ^1.2.5
  # Swap the connectivity package for this
  data_connection_checker: ^0.3.4
  # Mocktio
  mockito: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
  effective_dart: ^1.3.0

  # For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/jsons/
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
